name: pre-commit

on:
  pull_request:
  push:
    branches: [master]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.1.0
    - uses: actions/setup-python@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '1.17.11' # This should match .tool-versions
    - uses: pre-commit/action@v2.0.3
